usrmerge

diff --git a/debian/hardened-malloc-light-enable.postinst b/debian/hardened-malloc-light-enable.postinst
--- a/debian/hardened-malloc-light-enable.postinst
+++ b/debian/hardened-malloc-light-enable.postinst
@@ -23,7 +23,7 @@ create_hardened_malloc_light_enabled_status_file() {
    touch /var/lib/hardened-malloc-kicksecure-enable/enabled
 }
 
-if test -r /lib/x86_64-linux-gnu/libhardened_malloc-light.so ; then
+if test -r /usr/lib/x86_64-linux-gnu/libhardened_malloc-light.so ; then
    if grep -q libhardened_malloc-light.so /etc/ld.so.preload ; then
       echo "INFO: $0: libhardened_malloc-light.so already enabled in /etc/ld.so.preload, OK."
       create_hardened_malloc_light_enabled_status_file
@@ -38,7 +38,7 @@ if test -r /lib/x86_64-linux-gnu/libhardened_malloc-light.so ; then
       fi
    fi
 else
-   echo "ERROR: $0: file /lib/x86_64-linux-gnu/libhardened_malloc-light.so does not exist." >&2
+   echo "ERROR: $0: file /usr/lib/x86_64-linux-gnu/libhardened_malloc-light.so does not exist." >&2
 fi
 
 true "INFO: debhelper beginning here."
