fix: update to new path so /etc/ld.so.preload entry is removed on uninstallation

diff --git a/debian/hardened-malloc-light-enable.prerm b/debian/hardened-malloc-light-enable.prerm
--- a/debian/hardened-malloc-light-enable.prerm
+++ b/debian/hardened-malloc-light-enable.prerm
@@ -20,17 +20,17 @@ true "
 
 if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
    if test -r /etc/ld.so.preload ; then
-      if grep -q /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so /etc/ld.so.preload ; then
-         if LANG=C str_replace /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so "" /etc/ld.so.preload >/dev/null ; then
-            echo "INFO: $0: Removed /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so from /etc/ld.so.preload, OK."
+      if grep -q libhardened_malloc-light.so /etc/ld.so.preload ; then
+         if LANG=C str_replace libhardened_malloc-light.so "" /etc/ld.so.preload >/dev/null ; then
+            echo "INFO: $0: Removed libhardened_malloc-light.so from /etc/ld.so.preload, OK."
          else
-            echo "ERROR: $0: Removal of /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so from /etc/ld.so.preload failed." >&2
+            echo "ERROR: $0: Removal of libhardened_malloc-light.so from /etc/ld.so.preload failed." >&2
          fi
       else
-         echo "INFO: $0: /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so was already removed from /etc/ld.so.preload, OK."
+         echo "INFO: $0: libhardened_malloc-light.so was already removed from /etc/ld.so.preload, OK."
       fi
    else
-      echo "INFO: $0: /etc/ld.so.preload does not exist, therefore no need to remove /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so, OK."
+      echo "INFO: $0: /etc/ld.so.preload does not exist, therefore no need to remove libhardened_malloc-light.so, OK."
    fi
 
    rm -f /var/lib/hardened-malloc-kicksecure-enable/enabled
