fix: allow hardened malloc to be used by `setuid` programs
- no longer use full path names to hardened malloc library
- `set-user-id` hardened malloc library (`setuid`)

credit to @SkewedZeppelin for research:
https://gist.github.com/SkewedZeppelin/7f293d64c1c651bdc21526519d9e192b

https://forums.whonix.org/t/hardened-malloc-hardened-memory-allocator/7474/224

diff --git a/debian/hardened-malloc-light-enable.postinst b/debian/hardened-malloc-light-enable.postinst
--- a/debian/hardened-malloc-light-enable.postinst
+++ b/debian/hardened-malloc-light-enable.postinst
@@ -25,28 +25,41 @@ create_hardened_malloc_light_enabled_status_file() {
 
 ## legacy
 if test -f /etc/ld.so.preload ; then
+   ## forked libhardened_malloc_kicksecure.so was renamed to
+   ## original (unforked) upstream provided libhardened_malloc-light.so
    search="/usr/lib/libhardened_malloc.so/libhardened_malloc_kicksecure.so"
    replace="/usr/lib/libhardened_malloc.so/libhardened_malloc-light.so"
    file_name="/etc/ld.so.preload"
    LANG=C str_replace "$search" "$replace" "$file_name" || true
+
+   ## Should not use full path.
+   ## https://gist.github.com/SkewedZeppelin/7f293d64c1c651bdc21526519d9e192b
+   search="/usr/lib/libhardened_malloc.so/libhardened_malloc-light.so"
+   replace="libhardened_malloc-light.so"
+   file_name="/etc/ld.so.preload"
+   LANG=C str_replace "$search" "$replace" "$file_name" || true
+   search="/usr/lib/libhardened_malloc.so/libhardened_malloc.so"
+   replace="libhardened_malloc.so"
+   file_name="/etc/ld.so.preload"
+   LANG=C str_replace "$search" "$replace" "$file_name" || true
 fi
 
-if test -r /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so ; then
-   if grep -q /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so /etc/ld.so.preload ; then
-      echo "INFO: $0: /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so already enabled in /etc/ld.so.preload, OK."
+if test -r /lib/x86_64-linux-gnu/libhardened_malloc-light.so ; then
+   if grep -q libhardened_malloc-light.so /etc/ld.so.preload ; then
+      echo "INFO: $0: libhardened_malloc-light.so already enabled in /etc/ld.so.preload, OK."
       create_hardened_malloc_light_enabled_status_file
    else
       if test -f /var/lib/hardened-malloc-kicksecure-enable/enabled ; then
-         echo "INFO: $0: /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so was already previously enabled by this package, but currently is disabled. Leaving it as is, OK."
-      elif echo "/usr/lib/libhardened_malloc.so/libhardened_malloc-light.so" | tee "/etc/ld.so.preload" >/dev/null ; then
-         echo "INFO: $0: enabled /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so in /etc/ld.so.preload, OK."
+         echo "INFO: $0: libhardened_malloc-light.so was already previously enabled by this package, but currently is disabled. Leaving it as is, OK."
+      elif echo "libhardened_malloc-light.so" | tee "/etc/ld.so.preload" >/dev/null ; then
+         echo "INFO: $0: enabled libhardened_malloc-light.so in /etc/ld.so.preload, OK."
          create_hardened_malloc_light_enabled_status_file
       else
-         echo "ERROR: $0: could not write /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so to /etc/ld.so.preload." >&2
+         echo "ERROR: $0: could not write libhardened_malloc-light.so to /etc/ld.so.preload." >&2
       fi
    fi
 else
-   echo "ERROR: $0: file /usr/lib/libhardened_malloc.so/libhardened_malloc-light.so does not exist." >&2
+   echo "ERROR: $0: file /lib/x86_64-linux-gnu/libhardened_malloc-light.so does not exist." >&2
 fi
 
 true "INFO: debhelper beginning here."
